export const labelColors = {
  normal: "teal",
  fighting: "red",
  flying: "grape",
  poison: "violet",
  ground: "yellow",
  rock: "orange",
  bug: "lime",
  ghost: "grape",
  steel: "gray",
  fire: "red",
  water: "cyan",
  grass: "green",
  electric: "yellow",
  psychic: "red",
  ice: "blue",
  dragon: "violet",
  dark: "dark",
  fairy: "pink",
  unknown: "blue",
  shadow: "dark",
};
